# install-mysql.yaml

---
  - hosts: [k3smaster]
    become: true
    gather_facts: false

    vars_files:
      - ../secrets/secrets.yml

    tasks: 
      - name: install k3s master nodes
        throttle: 1
        shell: curl -sfL https://get.k3s.io | sh -s - server --node-taint CriticalAddonsOnly=true:NoExecute --tls-san 10.0.50.25
        environment:
          K3S_DATASTORE_ENDPOINT: '{{ k3s_datatore }}'
          K3S_TOKEN: '{{ k3s_join_token }}'